name: SonarQube
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronized, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Шаг диагностики (можно удалить после проверки)
      - name: Verify files
        working-directory: ./app
        run: |
          ls -la
          ./gradlew --version

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('app/**/*.gradle*') }}

      - name: Build
        working-directory: ./app
        run: |
          chmod +x gradlew
          ./gradlew build --no-daemon

      - name: SonarQube Analysis
        working-directory: ./app
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar --info --no-daemon
