name: SonarQube
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronized, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: app  # Ключевое изменение: клонируем в папку app/

      - name: Verify Gradle files
        run: |
          echo "=== Проверка файлов в app/ ==="
          ls -la app/
          echo "=== Права на gradlew ==="
          ls -la app/gradlew
          echo "=== Java версия ==="
          java -version

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Build with Gradle
        run: |
          cd app
          chmod +x gradlew
          ./gradlew build --no-daemon

      - name: SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd app
          ./gradlew sonar --info --no-daemon