name: SonarQube
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronized, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Переходим в нужную директорию
      - name: Change directory
        run: cd app && ls -la

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17

      - name: Build
        working-directory: ./app  # <-- Ключевое изменение!
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: SonarQube Analysis
        working-directory: ./app
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar --info
