name: SonarQube
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronized, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # УДАЛИТЕ path: app (это вызывает проблемы!)

      - name: Verify environment
        run: |
          echo "=== Структура проекта ==="
          ls -la
          echo "=== Содержимое app/ ==="
          ls -la app/
          [ -f "app/gradlew" ] || { echo "ERROR: gradlew not found!"; exit 1; }

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Build with Gradle
        working-directory: ./app  # Лучше чем cd
        run: |
          chmod +x gradlew
          ./gradlew build --no-daemon

      - name: SonarQube Analysis
        working-directory: ./app
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar --info --no-daemon
